export type AppView =
  | 'dashboard'
  | 'discussions'
  | 'decisions'
  | 'polls'
  | 'actions'
  | 'resources'
  | 'pulse-ai'
  | 'risks'
  | 'analytics'
  | 'meeting-summaries'
  | 'team'
  | 'notifications'
  | 'invitations'
  | 'audit-log'
  | 'settings'
  | 'integrations'
  | 'help';
