import { useMemo, useState } from 'react';
import { Check, Copy, Download, Package, Printer, X } from 'lucide-react';
import type {
  DecisionComment,
  DecisionHistoryEntry,
  DecisionOutcomeReview,
  DecisionResource,
  DecisionSummary,
  DecisionVoteTally,
  WorkspaceAction,
} from '@/types';

function clean(value: string | null | undefined) {
  return value?.trim() || '—';
}

function alignmentLabel(tally: DecisionVoteTally) {
  if (tally.total === 0) return 'No votes yet';
  const dominant = Math.max(tally.yes, tally.no, tally.needsInfo);
  const pct = Math.round((dominant / tally.total) * 100);
  if (tally.yes === dominant) return `${pct}% aligned toward Yes`;
  if (tally.no === dominant) return `${pct}% aligned toward No`;
  return `${pct}% requesting more information`;
}

function buildMarkdown(
  decision: DecisionSummary,
  resources: DecisionResource[],
  actions: WorkspaceAction[],
  comments: DecisionComment[],
  tally: DecisionVoteTally,
  history: DecisionHistoryEntry[],
  reviews: DecisionOutcomeReview[],
) {
  const lines = [
    `# PULSE Decision Brief — ${decision.title}`,
    '',
    `**Status:** ${decision.status}`,
    `**Outcome:** ${decision.outcome ?? 'Open'}`,
    `**Owner:** ${clean(decision.ownerName)}`,
    `**Deadline:** ${decision.deadline ? new Date(decision.deadline).toLocaleDateString() : '—'}`,
    `**Decided:** ${decision.decidedAt ? new Date(decision.decidedAt).toLocaleString() : '—'}`,
    `**Alignment:** ${alignmentLabel(tally)}`,
    '',
    '## Decision',
    clean(decision.description),
    '',
    '## Decision Gate',
    `- Already decided before: ${decision.gateAnswers?.alreadyDecided == null ? '—' : decision.gateAnswers.alreadyDecided ? 'Yes' : 'No'}`,
    `- Reversibility: ${decision.gateAnswers?.reversibility ?? '—'}`,
    `- Urgency: ${decision.gateAnswers?.urgency ?? '—'}`,
    `- Cost of delay: ${clean(decision.gateAnswers?.estimatedCostOfDelay)}`,
    `- Recommended process: ${decision.gateAnswers?.recommendedProcess ?? '—'}`,
    `- AI recommendation: ${clean(decision.gateAnswers?.aiRecommendation)}`,
    '',
    '## Vote tally',
    `- Yes: ${tally.yes}`,
    `- No: ${tally.no}`,
    `- Needs info: ${tally.needsInfo}`,
    `- Total votes: ${tally.total}`,
    '',
    '## Execution actions',
    ...(actions.length
      ? actions.map(
          (a) =>
            `- [${a.status === 'done' ? 'x' : ' '}] ${a.title}${a.ownerName ? ` — ${a.ownerName}` : ''}${
              a.deadline ? ` — due ${new Date(a.deadline).toLocaleDateString()}` : ''
            } (${a.status})`,
        )
      : ['- No actions recorded.']),
    '',
    '## Evidence & resources',
    ...(resources.length ? resources.map((r) => `- [${r.name}](${r.url ?? '#'})`) : ['- No resources recorded.']),
    '',
    '## Outcome tracking',
    `- Current score: ${decision.outcomeScore ?? 'Not reviewed'}`,
    `- Reversed: ${decision.isReversed ? `Yes — ${clean(decision.reversalReason)}` : 'No'}`,
    ...(reviews.length
      ? reviews.map(
          (r) =>
            `- ${r.reviewType}: ${r.status}${r.score ? ` — ${r.score}/5` : ''}${r.lessons ? ` — ${r.lessons}` : ''}`,
        )
      : ['- No outcome reviews yet.']),
    '',
    '## Decision history',
    ...(history.length
      ? history.map((h) => `- ${new Date(h.createdAt).toLocaleString()} — ${clean(h.changedByName)} — ${clean(h.note || h.status || h.outcome)}`)
      : ['- No history recorded.']),
    '',
    '## Discussion snapshot',
    `Comments captured: ${comments.length}`,
    ...(comments.slice(0, 8).map((c) => `- ${clean(c.authorName)}: ${c.body.slice(0, 180)}${c.body.length > 180 ? '…' : ''}`)),
    '',
    '---',
    `Generated by PULSE Decision OS on ${new Date().toLocaleString()}`,
  ];
  return lines.join('\n');
}

export function DecisionExecutionPackage({
  open,
  onClose,
  decision,
  resources,
  actions,
  comments,
  tally,
  history,
  reviews,
}: {
  open: boolean;
  onClose: () => void;
  decision: DecisionSummary;
  resources: DecisionResource[];
  actions: WorkspaceAction[];
  comments: DecisionComment[];
  tally: DecisionVoteTally;
  history: DecisionHistoryEntry[];
  reviews: DecisionOutcomeReview[];
}) {
  const [copied, setCopied] = useState(false);
  const markdown = useMemo(
    () => buildMarkdown(decision, resources, actions, comments, tally, history, reviews),
    [decision, resources, actions, comments, tally, history, reviews],
  );

  if (!open) return null;

  const copy = async () => {
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const download = () => {
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pulse-decision-brief-${decision.title.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  /** Opens a clean printable window so users can Save as PDF from the browser. */
  const printPdf = () => {
    const win = window.open('', '_blank', 'noopener,noreferrer,width=900,height=700');
    if (!win) return;
    const safe = markdown
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
    win.document.write(`<!doctype html>
<html><head><title>PULSE Decision Brief — ${decision.title.replace(/</g, '')}</title>
<style>
  body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif; margin: 40px; color: #111; line-height: 1.55; }
  h1 { font-size: 22px; margin-bottom: 8px; }
  pre { white-space: pre-wrap; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; }
  @media print { body { margin: 16px; } }
</style></head>
<body>
  <h1>PULSE Decision Brief</h1>
  <pre>${safe}</pre>
  <script>window.onload = () => { window.print(); }</script>
</body></html>`);
    win.document.close();
  };

  return (
    <div className="fixed inset-0 z-[85] grid place-items-center bg-black/70 p-4" onClick={onClose}>
      <div onClick={(e) => e.stopPropagation()} className="glass-strong flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-3xl">
        <div className="flex items-center justify-between border-b border-white/5 p-5">
          <div>
            <p className="flex items-center gap-1.5 text-[10px] uppercase tracking-[.2em] text-pulse-300">
              <Package className="h-3.5 w-3.5" /> Execution package
            </p>
            <h2 className="mt-1 font-display text-xl font-semibold">Decision Brief ready</h2>
            <p className="mt-1 text-xs text-ink-400">{alignmentLabel(tally)}</p>
          </div>
          <button className="icon-btn" onClick={onClose} aria-label="Close">
            <X />
          </button>
        </div>

        <pre className="m-4 flex-1 overflow-auto rounded-2xl border border-white/5 bg-black/20 p-4 text-xs leading-5 text-ink-300 whitespace-pre-wrap">
          {markdown}
        </pre>

        <div className="flex flex-wrap gap-2 border-t border-white/5 p-4">
          <button onClick={() => void copy()} className="secondary-btn flex-1 justify-center min-w-[140px]">
            {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? 'Copied' : 'Copy Markdown'}
          </button>
          <button onClick={download} className="secondary-btn flex-1 justify-center min-w-[140px]">
            <Download className="h-3.5 w-3.5" /> Download .md
          </button>
          <button onClick={printPdf} className="primary-btn flex-1 justify-center min-w-[140px]">
            <Printer className="h-3.5 w-3.5" /> Print / Save PDF
          </button>
        </div>
      </div>
    </div>
  );
}
