import { useMemo, useState } from 'react';
import { Check, Copy, Download, Package, X } from 'lucide-react';
import type { DecisionComment, DecisionHistoryEntry, DecisionOutcomeReview, DecisionResource, DecisionSummary, DecisionVoteTally, WorkspaceAction } from '@/types';

function clean(value: string | null | undefined) { return value?.trim() || '—'; }
function buildMarkdown(decision: DecisionSummary, resources: DecisionResource[], actions: WorkspaceAction[], comments: DecisionComment[], tally: DecisionVoteTally, history: DecisionHistoryEntry[], reviews: DecisionOutcomeReview[]) {
  const lines = [
    `# PULSE Decision Brief — ${decision.title}`,
    '', `**Status:** ${decision.status}`, `**Outcome:** ${decision.outcome ?? 'Open'}`, `**Owner:** ${clean(decision.ownerName)}`, `**Deadline:** ${decision.deadline ? new Date(decision.deadline).toLocaleDateString() : '—'}`, `**Decided:** ${decision.decidedAt ? new Date(decision.decidedAt).toLocaleString() : '—'}`,
    '', '## Decision', clean(decision.description),
    '', '## Decision Gate',
    `- Already decided: ${decision.gateAnswers?.alreadyDecided == null ? '—' : decision.gateAnswers.alreadyDecided ? 'Yes' : 'No'}`,
    `- Reversibility: ${decision.gateAnswers?.reversibility ?? '—'}`,
    `- Urgency: ${decision.gateAnswers?.urgency ?? '—'}`,
    `- Cost of delay: ${clean(decision.gateAnswers?.estimatedCostOfDelay)}`,
    `- Recommended process: ${decision.gateAnswers?.recommendedProcess ?? '—'}`,
    `- AI recommendation: ${clean(decision.gateAnswers?.aiRecommendation)}`,
    '', '## Vote', `- Yes: ${tally.yes}`, `- No: ${tally.no}`, `- Needs info: ${tally.needsInfo}`, `- Total: ${tally.total}`,
    '', '## Execution actions', ...(actions.length ? actions.map(a => `- [${a.status === 'done' ? 'x' : ' '}] ${a.title}${a.ownerName ? ` — ${a.ownerName}` : ''}${a.deadline ? ` — due ${new Date(a.deadline).toLocaleDateString()}` : ''}`) : ['- No actions recorded.']),
    '', '## Evidence & resources', ...(resources.length ? resources.map(r => `- [${r.name}](${r.url ?? '#'})`) : ['- No resources recorded.']),
    '', '## Outcome tracking', `- Current score: ${decision.outcomeScore ?? 'Not reviewed'}`, `- Reversed: ${decision.isReversed ? `Yes — ${clean(decision.reversalReason)}` : 'No'}`,
    ...(reviews.length ? reviews.map(r => `- ${r.reviewType}: ${r.status}${r.score ? ` — ${r.score}/5` : ''}${r.lessons ? ` — ${r.lessons}` : ''}`) : ['- No outcome reviews yet.']),
    '', '## Decision history', ...(history.length ? history.map(h => `- ${new Date(h.createdAt).toLocaleString()} — ${clean(h.note)}`) : ['- No history recorded.']),
    '', '## Discussion snapshot', `Comments captured: ${comments.length}`,
    '', '---', `Generated by PULSE on ${new Date().toLocaleString()}`,
  ];
  return lines.join('\n');
}

export function DecisionExecutionPackage({ open, onClose, decision, resources, actions, comments, tally, history, reviews }: { open: boolean; onClose: () => void; decision: DecisionSummary; resources: DecisionResource[]; actions: WorkspaceAction[]; comments: DecisionComment[]; tally: DecisionVoteTally; history: DecisionHistoryEntry[]; reviews: DecisionOutcomeReview[] }) {
  const [copied, setCopied] = useState(false);
  const markdown = useMemo(() => buildMarkdown(decision, resources, actions, comments, tally, history, reviews), [decision, resources, actions, comments, tally, history, reviews]);
  if (!open) return null;
  const copy = async () => { await navigator.clipboard.writeText(markdown); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  const download = () => { const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `pulse-decision-${decision.id}.md`; a.click(); URL.revokeObjectURL(url); };
  return <div className="fixed inset-0 z-[85] grid place-items-center bg-black/70 p-4" onClick={onClose}><div onClick={e => e.stopPropagation()} className="glass-strong flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-3xl"><div className="flex items-center justify-between border-b border-white/5 p-5"><div><p className="flex items-center gap-1.5 text-[10px] uppercase tracking-[.2em] text-pulse-300"><Package className="h-3.5 w-3.5" /> Execution package</p><h2 className="mt-1 font-display text-xl font-semibold">Decision Brief ready</h2></div><button className="icon-btn" onClick={onClose}><X /></button></div><pre className="m-4 flex-1 overflow-auto rounded-2xl border border-white/5 bg-black/20 p-4 text-xs leading-5 text-ink-300 whitespace-pre-wrap">{markdown}</pre><div className="flex gap-2 border-t border-white/5 p-4"><button onClick={() => void copy()} className="secondary-btn flex-1 justify-center">{copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}{copied ? 'Copied' : 'Copy Markdown'}</button><button onClick={download} className="primary-btn flex-1 justify-center"><Download className="h-3.5 w-3.5" /> Download .md</button></div></div></div>;
}
