import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BellRing, CheckCircle2, Clock3, Play, Power, RefreshCw, Zap } from 'lucide-react';
import { listAutomationRules, listAutomationRuns, runWorkspaceAutomations, updateAutomationRule, type AutomationRule, type AutomationRun } from '@/lib/pulseApi';

export function AutomationView({ workspaceId }: { workspaceId: string }) {
  const [rules,setRules]=useState<AutomationRule[]>([]); const [runs,setRuns]=useState<AutomationRun[]>([]); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(''); const [error,setError]=useState('');
  const load=async()=>{ try { setError(''); const [r,h]=await Promise.all([listAutomationRules(workspaceId),listAutomationRuns(workspaceId)]); setRules(r); setRuns(h); } catch(e){setError(e instanceof Error?e.message:'Could not load automations')} };
  useEffect(()=>{load()},[workspaceId]);
  const enabled=rules.filter(r=>r.enabled).length;
  const labels:Record<string,{title:string;desc:string;icon:typeof BellRing}>={action_due_soon:{title:'Upcoming action reminder',desc:'Notify owners when an open action is due within 48 hours.',icon:Clock3},action_overdue:{title:'Overdue action alert',desc:'Notify owners when an open action passes its deadline.',icon:AlertTriangle},high_priority_overdue:{title:'High-priority escalation',desc:'Flag overdue high-priority work so it cannot quietly disappear.',icon:Zap}};
  const run=async()=>{setBusy(true);setNotice('');setError('');try{const r=await runWorkspaceAutomations(workspaceId);setNotice(`Automation scan complete — ${r.notifications} notification${r.notifications===1?'':'s'} created.`);await load()}catch(e){setError(e instanceof Error?e.message:'Automation scan failed')}finally{setBusy(false)}};
  const toggle=async(r:AutomationRule)=>{try{await updateAutomationRule(r.id,!r.enabled);setRules(x=>x.map(v=>v.id===r.id?{...v,enabled:!v.enabled}:v))}catch(e){setError(e instanceof Error?e.message:'Could not update rule')}};
  const totalRuns=useMemo(()=>runs.length,[runs]);
  return <div className="mx-auto max-w-4xl space-y-4 px-4 pb-28 pt-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-1.5 text-xs uppercase tracking-[.2em] text-pulse-300"><Zap className="h-3.5 w-3.5"/> Intelligence</p><h1 className="mt-1 font-display text-2xl font-semibold">Automation</h1><p className="mt-1 text-xs text-ink-500">Let PULSE watch execution and take care of routine follow-up.</p></div><button onClick={run} disabled={busy} className="primary-btn"><Play className="h-3.5 w-3.5"/>{busy?'Scanning…':'Run automation scan'}</button></div>
    {notice&&<div className="glass rounded-2xl border border-flux-500/20 p-3 text-xs text-flux-300"><CheckCircle2 className="mr-1.5 inline h-4 w-4"/>{notice}</div>}
    {error&&<div className="glass rounded-2xl border border-ember-500/20 p-3 text-xs text-ember-300">{error}</div>}
    <div className="grid grid-cols-3 gap-2"><div className="glass rounded-2xl p-3"><p className="text-[10px] uppercase tracking-wider text-ink-500">Rules</p><p className="mt-1 text-xl font-semibold">{rules.length}</p></div><div className="glass rounded-2xl p-3"><p className="text-[10px] uppercase tracking-wider text-ink-500">Enabled</p><p className="mt-1 text-xl font-semibold">{enabled}</p></div><div className="glass rounded-2xl p-3"><p className="text-[10px] uppercase tracking-wider text-ink-500">Scans</p><p className="mt-1 text-xl font-semibold">{totalRuns}</p></div></div>
    <section className="glass rounded-2xl p-4"><div className="mb-3 flex items-center gap-2"><BellRing className="h-4 w-4 text-pulse-300"/><div><h2 className="text-sm font-semibold">Automation rules</h2><p className="text-[11px] text-ink-500">These rules use your real workspace actions.</p></div></div><div className="space-y-2">{rules.map(r=>{const m=labels[r.trigger]??labels.action_overdue;const Icon=m.icon;return <div key={r.id} className="flex items-center gap-3 rounded-xl border border-white/5 bg-white/[.02] p-3"><Icon className="h-4 w-4 shrink-0 text-pulse-300"/><div className="min-w-0 flex-1"><p className="text-sm font-medium">{m.title}</p><p className="text-[11px] text-ink-500">{m.desc}</p></div><button onClick={()=>toggle(r)} className={`rounded-full border px-2.5 py-1 text-[10px] ${r.enabled?'border-flux-500/30 text-flux-300':'border-white/10 text-ink-500'}`}><Power className="mr-1 inline h-3 w-3"/>{r.enabled?'On':'Off'}</button></div>})}{rules.length===0&&<p className="py-6 text-center text-xs text-ink-500">Run your first automation scan to initialize the workspace rules.</p>}</div></section>
    <section className="glass rounded-2xl p-4"><div className="mb-3 flex items-center gap-2"><RefreshCw className="h-4 w-4 text-pulse-300"/><h2 className="text-sm font-semibold">Automation history</h2></div><div className="space-y-2">{runs.slice(0,8).map(r=><div key={r.id} className="flex items-center gap-3 border-b border-white/5 py-2 last:border-0"><Clock3 className="h-3.5 w-3.5 text-ink-600"/><div className="flex-1"><p className="text-xs text-ink-300">{r.ruleName}</p><p className="text-[10px] text-ink-600">{new Date(r.createdAt).toLocaleString()}</p></div><span className="text-[10px] text-ink-500">{r.actionCount} matched</span></div>)}{runs.length===0&&<p className="py-6 text-center text-xs text-ink-500">No automation runs yet.</p>}</div></section>
  </div>
}
